// <auto-generated />
using System;
using AbyssFm.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AbyssFm.Api.Migrations
{
    [DbContext(typeof(AbyssFmDbContext))]
    [Migration("20260720165323_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AbyssFm.Api.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("album_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlbumId"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_image_url");

                    b.Property<string>("CoverTheme")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cover_theme");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("release_year");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("Title", "ArtistId")
                        .IsUnique();

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("AbyssFm.Api.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtistId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("ArtistId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("AbyssFm.Api.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("GenreId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("AbyssFm.Api.Models.MoodTag", b =>
                {
                    b.Property<int>("MoodTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mood_tag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MoodTagId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayIcon")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("display_icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("MoodTagId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("mood_tags", (string)null);
                });

            modelBuilder.Entity("AbyssFm.Api.Models.RecommendationResult", b =>
                {
                    b.Property<int>("RecommendationResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recommendation_result_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecommendationResultId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reasons_json");

                    b.Property<Guid>("RecommendationSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_session_id");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<int>("SongId")
                        .HasColumnType("integer")
                        .HasColumnName("song_id");

                    b.HasKey("RecommendationResultId");

                    b.HasIndex("RecommendationSessionId");

                    b.HasIndex("SongId");

                    b.HasIndex("RecommendationSessionId", "Rank")
                        .IsUnique();

                    b.HasIndex("RecommendationSessionId", "SongId")
                        .IsUnique();

                    b.ToTable("recommendation_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_recommendation_results_rank_positive", "rank > 0");

                            t.HasCheckConstraint("ck_recommendation_results_score_non_negative", "score >= 0");
                        });
                });

            modelBuilder.Entity("AbyssFm.Api.Models.RecommendationSession", b =>
                {
                    b.Property<Guid>("RecommendationSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_session_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("SelectedGenreIdsJson")
                        .HasColumnType("text")
                        .HasColumnName("selected_genre_ids_json");

                    b.Property<string>("SelectedMoodTagIdsJson")
                        .HasColumnType("text")
                        .HasColumnName("selected_mood_tag_ids_json");

                    b.Property<string>("SelectedVibeTagIdsJson")
                        .HasColumnType("text")
                        .HasColumnName("selected_vibe_tag_ids_json");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<short?>("TargetDanceability")
                        .HasColumnType("smallint")
                        .HasColumnName("target_danceability");

                    b.Property<short?>("TargetDarkness")
                        .HasColumnType("smallint")
                        .HasColumnName("target_darkness");

                    b.Property<short?>("TargetEnergy")
                        .HasColumnType("smallint")
                        .HasColumnName("target_energy");

                    b.Property<short?>("TargetInstrumentalness")
                        .HasColumnType("smallint")
                        .HasColumnName("target_instrumentalness");

                    b.Property<short?>("TargetValence")
                        .HasColumnType("smallint")
                        .HasColumnName("target_valence");

                    b.HasKey("RecommendationSessionId");

                    b.ToTable("recommendation_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_recommendation_sessions_target_danceability_range", "target_danceability IS NULL OR target_danceability BETWEEN 1 AND 10");

                            t.HasCheckConstraint("ck_recommendation_sessions_target_darkness_range", "target_darkness IS NULL OR target_darkness BETWEEN 1 AND 10");

                            t.HasCheckConstraint("ck_recommendation_sessions_target_energy_range", "target_energy IS NULL OR target_energy BETWEEN 1 AND 10");

                            t.HasCheckConstraint("ck_recommendation_sessions_target_instrumentalness_range", "target_instrumentalness IS NULL OR target_instrumentalness BETWEEN 1 AND 10");

                            t.HasCheckConstraint("ck_recommendation_sessions_target_valence_range", "target_valence IS NULL OR target_valence BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("AbyssFm.Api.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("song_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SongId"));

                    b.Property<int?>("AlbumId")
                        .HasColumnType("integer")
                        .HasColumnName("album_id");

                    b.Property<string>("CoverTheme")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cover_theme");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<short>("Danceability")
                        .HasColumnType("smallint")
                        .HasColumnName("danceability");

                    b.Property<short>("Darkness")
                        .HasColumnType("smallint")
                        .HasColumnName("darkness");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<short>("Energy")
                        .HasColumnType("smallint")
                        .HasColumnName("energy");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("text")
                        .HasColumnName("external_url");

                    b.Property<short>("Instrumentalness")
                        .HasColumnType("smallint")
                        .HasColumnName("instrumentalness");

                    b.Property<string>("PreviewUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_url");

                    b.Property<int>("PrimaryArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("primary_artist_id");

                    b.Property<int>("PrimaryGenreId")
                        .HasColumnType("integer")
                        .HasColumnName("primary_genre_id");

                    b.Property<int?>("TempoBpm")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_bpm");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<short>("Valence")
                        .HasColumnType("smallint")
                        .HasColumnName("valence");

                    b.HasKey("SongId");

                    b.HasIndex("AlbumId");

                    b.HasIndex("Danceability");

                    b.HasIndex("Darkness");

                    b.HasIndex("Energy");

                    b.HasIndex("Instrumentalness");

                    b.HasIndex("PrimaryArtistId");

                    b.HasIndex("PrimaryGenreId");

                    b.HasIndex("Valence");

                    b.HasIndex("Title", "PrimaryArtistId", "AlbumId")
                        .IsUnique();

                    b.ToTable("songs", null, t =>
                        {
                            t.HasCheckConstraint("ck_songs_danceability_range", "danceability BETWEEN 1 AND 10");

                            t.HasCheckConstraint("ck_songs_darkness_range", "darkness BETWEEN 1 AND 10");

                            t.HasCheckConstraint("ck_songs_energy_range", "energy BETWEEN 1 AND 10");

                            t.HasCheckConstraint("ck_songs_instrumentalness_range", "instrumentalness BETWEEN 1 AND 10");

                            t.HasCheckConstraint("ck_songs_valence_range", "valence BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("AbyssFm.Api.Models.SongGenre", b =>
                {
                    b.Property<int>("SongId")
                        .HasColumnType("integer")
                        .HasColumnName("song_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.Property<short>("Weight")
                        .HasColumnType("smallint")
                        .HasColumnName("weight");

                    b.HasKey("SongId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("song_genres", null, t =>
                        {
                            t.HasCheckConstraint("ck_song_genres_weight_range", "weight BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("AbyssFm.Api.Models.SongMoodTag", b =>
                {
                    b.Property<int>("SongId")
                        .HasColumnType("integer")
                        .HasColumnName("song_id");

                    b.Property<int>("MoodTagId")
                        .HasColumnType("integer")
                        .HasColumnName("mood_tag_id");

                    b.Property<short>("Weight")
                        .HasColumnType("smallint")
                        .HasColumnName("weight");

                    b.HasKey("SongId", "MoodTagId");

                    b.HasIndex("MoodTagId");

                    b.ToTable("song_mood_tags", null, t =>
                        {
                            t.HasCheckConstraint("ck_song_mood_tags_weight_range", "weight BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("AbyssFm.Api.Models.SongVibeTag", b =>
                {
                    b.Property<int>("SongId")
                        .HasColumnType("integer")
                        .HasColumnName("song_id");

                    b.Property<int>("VibeTagId")
                        .HasColumnType("integer")
                        .HasColumnName("vibe_tag_id");

                    b.Property<short>("Weight")
                        .HasColumnType("smallint")
                        .HasColumnName("weight");

                    b.HasKey("SongId", "VibeTagId");

                    b.HasIndex("VibeTagId");

                    b.ToTable("song_vibe_tags", null, t =>
                        {
                            t.HasCheckConstraint("ck_song_vibe_tags_weight_range", "weight BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("AbyssFm.Api.Models.VibeTag", b =>
                {
                    b.Property<int>("VibeTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vibe_tag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VibeTagId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayIcon")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("display_icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("VibeTagId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("vibe_tags", (string)null);
                });

            modelBuilder.Entity("AbyssFm.Api.Models.Album", b =>
                {
                    b.HasOne("AbyssFm.Api.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("AbyssFm.Api.Models.RecommendationResult", b =>
                {
                    b.HasOne("AbyssFm.Api.Models.RecommendationSession", "RecommendationSession")
                        .WithMany("RecommendationResults")
                        .HasForeignKey("RecommendationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AbyssFm.Api.Models.Song", "Song")
                        .WithMany("RecommendationResults")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecommendationSession");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("AbyssFm.Api.Models.Song", b =>
                {
                    b.HasOne("AbyssFm.Api.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AbyssFm.Api.Models.Artist", "PrimaryArtist")
                        .WithMany("Songs")
                        .HasForeignKey("PrimaryArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AbyssFm.Api.Models.Genre", "PrimaryGenre")
                        .WithMany("PrimaryGenreSongs")
                        .HasForeignKey("PrimaryGenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("PrimaryArtist");

                    b.Navigation("PrimaryGenre");
                });

            modelBuilder.Entity("AbyssFm.Api.Models.SongGenre", b =>
                {
                    b.HasOne("AbyssFm.Api.Models.Genre", "Genre")
                        .WithMany("SongGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AbyssFm.Api.Models.Song", "Song")
                        .WithMany("SongGenres")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("AbyssFm.Api.Models.SongMoodTag", b =>
                {
                    b.HasOne("AbyssFm.Api.Models.MoodTag", "MoodTag")
                        .WithMany("SongMoodTags")
                        .HasForeignKey("MoodTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AbyssFm.Api.Models.Song", "Song")
                        .WithMany("SongMoodTags")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoodTag");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("AbyssFm.Api.Models.SongVibeTag", b =>
                {
                    b.HasOne("AbyssFm.Api.Models.Song", "Song")
                        .WithMany("SongVibeTags")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AbyssFm.Api.Models.VibeTag", "VibeTag")
                        .WithMany("SongVibeTags")
                        .HasForeignKey("VibeTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("VibeTag");
                });

            modelBuilder.Entity("AbyssFm.Api.Models.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("AbyssFm.Api.Models.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("AbyssFm.Api.Models.Genre", b =>
                {
                    b.Navigation("PrimaryGenreSongs");

                    b.Navigation("SongGenres");
                });

            modelBuilder.Entity("AbyssFm.Api.Models.MoodTag", b =>
                {
                    b.Navigation("SongMoodTags");
                });

            modelBuilder.Entity("AbyssFm.Api.Models.RecommendationSession", b =>
                {
                    b.Navigation("RecommendationResults");
                });

            modelBuilder.Entity("AbyssFm.Api.Models.Song", b =>
                {
                    b.Navigation("RecommendationResults");

                    b.Navigation("SongGenres");

                    b.Navigation("SongMoodTags");

                    b.Navigation("SongVibeTags");
                });

            modelBuilder.Entity("AbyssFm.Api.Models.VibeTag", b =>
                {
                    b.Navigation("SongVibeTags");
                });
#pragma warning restore 612, 618
        }
    }
}
